### PR TITLE
at least it compiled. maybe

### PR DESCRIPTION
**Pull request by adamdruppe**
I don't really trust it but `dub build` didn't fail on my box.

### CODE REVIEW

**Comment by adamdruppe** [comment]
can anyone try it in a real world context and see if it actually works? the generated bindings included in the PR are for Win 64.

**Comment by John-Colvin** [comment]
I can't get it to work with `dub test --compiler=ldc2` with `ldc-1.17.0` (what we are currently using)

**Comment by adamdruppe** [comment]
what did you do and what did it do?

**Comment by John-Colvin** [comment]
Semi-false-alarm, I had some stuff left over in my build from an old experiment i did. I actually can't get close to the failure point I was at then

How did you go about building mongo-c-driver? I don't see any instructions for windows and in the version we have as a submodule there isn't any bundled bson source code (later versions of mongo-c-driver do have it)

**Comment by adamdruppe** [comment]
I just downloaded from github and did the usual cmake process, it picked up the Visual Studio install on my box and used it. I could possibly just send you the zip.

**Comment by John-Colvin** [comment]
do you mean bson or mongo? mongo-c-driver is a submodule of this project, did you use that version?

**Comment by adamdruppe** [comment]
Looks like no, the mongo-c-driver is completely different on my computer than on the git.

I downloaded it from github https://github.com/mongodb/mongo-c-driver and followed the instructions there. Then it looks like I copied the resultant artifacts from c:\program files back into the local directory.

**Comment by adamdruppe** [comment]
[mongo-c-driver.zip](https://github.com/symmetryinvestments/mondo/files/3869353/mongo-c-driver.zip)
there's the zip of the result

**Comment by adamdruppe** [comment]
I do not recall why I went to github, probably simply because I didn't realize it was there... I don't think I did the recursive submodule pull so the directory would have been empty.

**Pull request merged**
